---
title: "groundwater depletion"
author: "Shuhan Song"
date: "November 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

###Set the scene

In 2000: 

- initial flow in: 12.8 $\times$ 10<sup>9

- initial flow out: 18.2 $\times$ 10<sup>9

In 2050:

- initial flow in: 10.3 $\times$ 10<sup>9

- initial flow out: 27 $\times$ 10<sup>9

```{r}
groundwater <- data.frame(year = c(2000, 2050), flow_in = c(12.8, 8.5), flow_out = c(18.2, 18.5))

ggplot(data = groundwater, aes(x = year)) +
  geom_ribbon(aes(ymin = flow_in, ymax = flow_out),
              alpha = 0.1) +
  geom_point(aes(y = flow_in), color = "blue") +
  geom_point(aes(y = flow_out), color = "red") +
  geom_line(aes(y = flow_in), color = "blue") +
  geom_line(aes(y = flow_out), color = "red") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 30)) +
  labs(x = "Year", 
       y = "Groundwater flow (10^9 m^3)", 
       title = "Figure 1: California groundwater flow 2000-2050",
       caption = "Blue line represent input (2000 = 12.8, 2050 = 8.5) \n Red line represent loss (2000 = 18.2, 2050 = 18.5)") +
  geom_text(x = 2030, y = 8,
            label = "flow in",
            color = "blue") +
  geom_text(x = 2030, y = 21,
            label = "flow out",
            color = "red") +
  geom_text(x = 2030, y = 15,
            label = "the amount of depletion",
            color = "black") 

ggsave("groundwater flow 2000-2050.jpg", height = 5, width = 6)
```

####fit the lines of flow

```{r}
flow_in <- lm(flow_in ~ year, data = groundwater)
flow_in
flow_in_eqn <- function(year){
  flow_in$coefficients[1] + flow_in$coefficients[2]*year
  }

flow_out <- lm(flow_out ~ year, data = groundwater)
flow_out

flow_out_eqn <- function(year){
  flow_out$coefficients[1] + flow_out$coefficients[2]*year
}

```

####calculate groundwater stock in 2050
```{r}
cum_flow_change <- function(year){
  0.5*(year-2000)*(flow_in_eqn(year) - flow_out_eqn(year)) + (flow_in_eqn(2000)-flow_out_eqn(2000))*0.5*(year-2000)
}

stock_exp <- 350
stock_min <- 190
stock_max <- 550

stock_fin_exp <- stock_exp + cum_flow_change(2046)
stock_fin_exp
stock_fin_min <- stock_min + cum_flow_change(2028)
stock_fin_min
stock_fin_max <- stock_max + cum_flow_change(2066)
stock_fin_max
```

####How does groundwater stock change 2000-2050?
```{r}
year <- seq(from = 2000, to = 2050)
cum_flow_change <- cum_flow_change(year)

stock_year <- data.frame(year = year, 
                         expected_volume = stock_exp + cum_flow_change, 
                         lower_limit = stock_min + cum_flow_change,
                         upper_limit = stock_max + cum_flow_change) %>% 
  pivot_longer(expected_volume:upper_limit, names_to = "stock_type", values_to = "stock_value")

ggplot(data = stock_year, aes(x = year, y = stock_value)) +
  geom_point(aes(color = stock_type),
             alpha = 0.5,
             size = 1) +
  geom_line(aes(color = stock_type)) +
  theme_minimal() +
  geom_line(y = 0, 
            linetype = 2) +
  labs(x = "Year",
       y = "Groundwater stock (10^9 m^3)",
       title = "Figure 2: California groundwater stock 2000-2050") +
  scale_color_discrete(name = "Stock type",
                       labels = c("expected value", "lower limit", "upper limit"))

ggsave("groundwater stock 2000-2050.jpg", height = 4, width = 7)
```


